/** @type {import('czg').UserConfig} */
export default {
  extends: ["@commitlint/config-conventional"],
  types: [
    { value: "feat", name: "feat:     New feature" },
    { value: "fix", name: "fix:      Bug fix" },
    { value: "docs", name: "docs:     Documentation only changes" },
    { value: "style", name: "style:    Code style (formatting, etc)" },
    { value: "refactor", name: "refactor: Code change without bug fix or feature" },
    { value: "perf", name: "perf:     Performance improvements" },
    { value: "test", name: "test:     Adding or correcting tests" },
    { value: "build", name: "build:    Build system or dependencies" },
    { value: "ci", name: "ci:       CI configuration" },
    { value: "chore", name: "chore:    Other changes" },
    { value: "revert", name: "revert:   Reverts a previous commit" },
    { value: "release", name: "release:  Release commit" },
  ],
  scopes: [
    "core",
    "core-types",
    "route-tree",
    "search-params",
    "type-guards",
    "helpers",
    "browser-plugin",
    "logger-plugin",
    "persistent-params-plugin",
    "react",
    "benchmarks",
    "deps",
    "config",
    "ci",
  ],
  scopeOverrides: {
    fix: [
      { name: "core" },
      { name: "core-types" },
      { name: "route-tree" },
      { name: "search-params" },
      { name: "type-guards" },
      { name: "helpers" },
      { name: "browser-plugin" },
      { name: "logger-plugin" },
      { name: "persistent-params-plugin" },
      { name: "react" },
    ],
  },
  allowEmptyScopes: true,
  allowCustomScopes: true,
  allowBreakingChanges: ["feat", "fix"],
  upperCaseSubject: false,
  markBreakingChangeMode: true,
  breaklineNumber: 100,
  breaklineChar: "|",
  issuePrefixes: [
    { value: "closed", name: "closed:   ISSUES has been processed" },
  ],
  customIssuePrefixAlign: "top",
  emptyIssuePrefixAlias: "skip",
  customIssuePrefixAlias: "custom",
  confirmColorize: true,
  minSubjectLength: 0,
  defaultSubject: "",
  messages: {
    type: "Select the type of change that you're committing:",
    scope: "Denote the SCOPE of this change (optional):",
    customScope: "Denote the SCOPE of this change:",
    subject: "Write a SHORT, IMPERATIVE tense description of the change:\n",
    body: 'Provide a LONGER description of the change (optional). Use "|" to break new line:\n',
    breaking:
      'List any BREAKING CHANGES (optional). Use "|" to break new line:\n',
    footerPrefixesSelect:
      "Select the ISSUES type of changeList by this change (optional):",
    customFooterPrefix: "Input ISSUES prefix:",
    footer: "List any ISSUES by this change. E.g.: #31, #34:\n",
    confirmCommit: "Are you sure you want to proceed with the commit above?",
  },
};
