packages:
  - 'packages/*'

# TODO: remove after 2026-03-01 (24h exclusion for turbo 2.8.12)
minimumReleaseAgeExclude:
  - turbo@2.8.12
  - turbo-darwin-arm64@2.8.12
  - turbo-linux-64@2.8.12
  - turbo-linux-arm64@2.8.12
  - eslint-config-turbo@2.8.12
  - eslint-plugin-turbo@2.8.12
