import { defineConfig, mergeConfig } from "vitest/config";
import { commonConfig } from "./vitest.config.common.mjs";

/**
 * Vitest configuration for property-based testing
 *
 * Property-based tests verify mathematical invariants and behavioral properties
 * using randomized inputs generated by fast-check.
 *
 * Extends common config with:
 * - Coverage disabled (focus on invariants, not coverage)
 * - Extended timeout (30s for multiple iterations)
 * - Reduced workers (2 for stability)
 *
 * @see https://vitest.dev/config/
 * @see https://fast-check.dev/
 */
export default mergeConfig(
  commonConfig,
  defineConfig({
    test: {
      /**
       * Coverage configuration - disabled for property tests
       * Property tests focus on invariants, not coverage
       */
      coverage: {
        enabled: false,
      },

      /**
       * Reporter configuration
       */
      reporters: ["default"],

      /**
       * Test filtering - only property-based tests
       */
      include: ["./packages/*/tests/property/**/*.properties.ts?(x)"],
      exclude: ["node_modules", "dist", ".idea", ".git", ".cache", "coverage"],

      /**
       * Timeout configuration
       * Property-based tests run multiple iterations (50-10000+ runs per test)
       * and need more time than standard example-based tests
       */
      testTimeout: 30000, // 30 seconds per test
      hookTimeout: 10000, // 10 seconds for hooks
      teardownTimeout: 10000, // 10 seconds for cleanup

      /**
       * Worker configuration
       * Limit parallelism to prevent "Timeout calling onTaskUpdate" errors
       * during long-running property-based tests
       */
      maxWorkers: 2,

      // Use threads pool for better performance with async tests
      pool: "threads",

      /**
       * Disable automatic mock cleanup per iteration
       *
       * @fast-check/vitest 0.3.0 fires beforeEach/afterEach per property iteration.
       * With restoreMocks/mockReset enabled, vi.spyOn() spies are destroyed after
       * every iteration — creating/destroying 65k+ spies causes severe slowdowns.
       * Property tests manage their own mock lifecycle via beforeAll/afterAll.
       */
      restoreMocks: false,
      mockReset: false,
    },
  }),
);
