import { defineConfig, mergeConfig } from "vitest/config";
import { commonConfig } from "./vitest.config.common.mjs";

/**
 * Vitest configuration for property-based testing
 *
 * Property-based tests verify mathematical invariants and behavioral properties
 * using randomized inputs generated by fast-check.
 *
 * Extends common config with:
 * - Coverage disabled (focus on invariants, not coverage)
 * - Extended timeout (30s for multiple iterations)
 * - Reduced workers (2 for stability)
 *
 * @see https://vitest.dev/config/
 * @see https://fast-check.dev/
 */
export default mergeConfig(
  commonConfig,
  defineConfig({
    test: {
      /**
       * Coverage configuration - disabled for property tests
       * Property tests focus on invariants, not coverage
       */
      coverage: {
        enabled: false,
      },

      /**
       * Reporter configuration
       */
      reporters: process.env.CI ? ["default", "github-actions"] : ["default"],

      /**
       * Test filtering - only property-based tests
       */
      include: ["./packages/*/tests/property/**/*.properties.ts?(x)"],
      exclude: ["node_modules", "dist", ".idea", ".git", ".cache", "coverage"],

      /**
       * Timeout configuration.
       *
       * Property cells run 50–10 000+ iterations and need more time than an
       * example-based test. What sizes the number is not the iteration count
       * but the WORST CASE ratio between a cell's local wall-time and what a
       * contended CI runner does to it.
       *
       * ⚠ **60 s was not "generous headroom" — it was 52×, and a runner reached
       * 85× (#2107).** Measured 2026-09-05: the slowest cell in the suite,
       * `utils/logger/callback.properties.ts` → "same parameters give same
       * result", runs **1159 ms** locally. Against 60 s that is 52× headroom.
       * On the post-merge run of `a9b45fa6c` the same file took **257 s**
       * against 4.1 s locally — 63× — and its two slowest cells individually
       * reached 56× and 85×. Both timed out, the post-merge went red, and
       * because `changesets.yml` triggers on a SUCCESSFUL `workflow_run`, the
       * release it was gating was never created.
       *
       * ⚑ 300 s is 259× on that cell, three times the worst contention
       * observed. The cost of the larger number is bounded and small: a cell
       * that genuinely HANGS holds CI five minutes instead of one, and a hang
       * never completes, so no finite value catches it sooner. The cost of the
       * smaller number was a stranded release.
       */
      testTimeout: 300000, // 5 minutes per test — see the ratio above
      hookTimeout: 10000, // 10 seconds for hooks
      teardownTimeout: 10000, // 10 seconds for cleanup

      /**
       * Worker configuration
       * Limit parallelism to prevent "Timeout calling onTaskUpdate" errors
       * during long-running property-based tests
       */
      maxWorkers: 2,

      // Use threads pool for better performance with async tests
      pool: "threads",

      /**
       * Disable automatic mock cleanup per iteration
       *
       * @fast-check/vitest 0.3.0 fires beforeEach/afterEach per property iteration.
       * With restoreMocks/mockReset enabled, vi.spyOn() spies are destroyed after
       * every iteration — creating/destroying 65k+ spies causes severe slowdowns.
       * Property tests manage their own mock lifecycle via beforeAll/afterAll.
       */
      restoreMocks: false,
      mockReset: false,
    },
  }),
);
