import {
  afterAll,
  afterEach,
  beforeAll,
  describe,
  expect,
  it,
  vi,
} from "vitest";

import {
  __resetRegistryForTests,
  ensureRegistryPromise,
} from "../../src/shared-ssr/deferRegistryClient";
import { getDeferBootstrapScript } from "../../src/shared-ssr/deferWireFormat";

const noop = (): void => undefined;

/**
 * Stress coverage for the client-side `__rrDeferRegistry__` global Map.
 *
 * Three contracts pinned here:
 *
 *   1. **Leak-by-design.** The Map accumulates one entry per unique
 *      deferred key for the lifetime of the page. No release path exists
 *      — each entry is a Promise that may still settle later when an
 *      inline `<script>__rrDefer__(key, json)</script>` lands. Documented
 *      here as an explicit assertion so a future refactor that adds a
 *      release path (`releaseKey(key)` / WeakMap-by-route / per-clone
 *      isolation) updates this anchor instead of silently slipping
 *      semantics.
 *
 *   2. **Per-key idempotency.** N calls to `ensureRegistryPromise(k)`
 *      for the same `k` return the same Promise and leave a single Map
 *      entry. A regression that recreates the entry on every call would
 *      detach the captured Promise reference held by `useDeferred()`
 *      from the one the settle script resolves — UI would hang on the
 *      orphaned Promise forever.
 *
 *   3. **Bootstrap idempotency under load.** `getDeferBootstrapScript()`
 *      returns ES5-ish source whose `if(!R)R=...` guards an existing
 *      registry. Re-evaluating the bootstrap N times must NOT rebuild
 *      the registry — otherwise captured Promises from earlier in the
 *      page lifecycle would be orphaned.
 */
describe("__rrDeferRegistry__ growth and idempotency", () => {
  beforeAll(() => {
    vi.spyOn(console, "warn").mockImplementation(noop);
    vi.spyOn(console, "error").mockImplementation(noop);
  });

  afterEach(() => {
    __resetRegistryForTests();
  });

  afterAll(() => {
    vi.restoreAllMocks();
  });

  it("1000 unique keys: Map.size === 1000 (linear growth, leak by design)", () => {
    // 1000 unique keys is well above any realistic per-session ceiling
    // (single-digit deferred keys per route × dozens of navigations per
    // session ≈ low hundreds). 10x that bound exercises the growth
    // semantics without burning CI time. Per-entry footprint is
    // ~200-2000 bytes (closure + native Promise), so 1000 keys ≈ 200KB.
    //
    // The returned Promise is intentionally discarded — the side-effect
    // (Map entry creation) is what's under test, not the Promise itself.
    // `void` marks the intent for the no-floating-promises rule.
    for (let i = 0; i < 1000; i++) {
      void ensureRegistryPromise(`key-${i}`);
    }

    const registry = (
      globalThis as { __rrDeferRegistry__?: Map<string, unknown> }
    ).__rrDeferRegistry__;

    expect(registry).toBeDefined();
    expect(registry!.size).toBe(1000);

    // Locking the contract: no release path. If a future refactor adds
    // `releaseKey(...)`, this assertion will fire and force a doc update
    // on the leak-by-design comment in deferRegistry.ts.
    const maybeRelease = (registry as unknown as { releaseKey?: unknown })
      .releaseKey;

    expect(maybeRelease).toBeUndefined();
  });

  it("10000 repeats of the same key: Map.size stays === 1 (per-key idempotency)", () => {
    const first = ensureRegistryPromise("only");

    for (let i = 0; i < 10_000; i++) {
      const each = ensureRegistryPromise("only");

      // Per-call assertion would be 10K micro-asserts — collapse to one
      // reference-identity check at the end. A regression that creates a
      // new Promise on each call would surface immediately on the first
      // iteration's `!== first`, but the assertion shape stays cheap.
      if (each !== first) {
        throw new Error(`identity regression at i=${i}`);
      }
    }

    const registry = (
      globalThis as { __rrDeferRegistry__?: Map<string, unknown> }
    ).__rrDeferRegistry__;

    expect(registry!.size).toBe(1);
  });

  it("1000 bootstrap evals after registry was populated: registry instance preserved (no orphaned promises)", () => {
    // Pre-populate the registry via the SDK path — this is what
    // `reconstructDeferredFromHydration` does during the post-hydration
    // start interceptor.
    const captured = ensureRegistryPromise("captured");

    const registryBefore = (
      globalThis as { __rrDeferRegistry__?: Map<string, unknown> }
    ).__rrDeferRegistry__;

    // Run the inline bootstrap source 1000 times. The script is
    // generated by `getDeferBootstrapScript()` (no user input), so
    // `new Function(source)` is safe — same eval pattern as the
    // functional anchors in `defer-registry.test.ts`.
    // eslint-disable-next-line @typescript-eslint/no-implied-eval, sonarjs/code-eval -- const script source
    const bootstrap = new Function(getDeferBootstrapScript());

    for (let i = 0; i < 1000; i++) {
      bootstrap();
    }

    const registryAfter = (
      globalThis as { __rrDeferRegistry__?: Map<string, unknown> }
    ).__rrDeferRegistry__;

    // Reference identity must survive — losing it would orphan every
    // already-captured `useDeferred()` Promise on the page.
    expect(registryAfter).toBe(registryBefore);
    expect(registryAfter!.has("captured")).toBe(true);

    // The captured Promise itself must still be the one
    // `ensureRegistryPromise("captured")` would return — sanity check on
    // the upstream contract that the bootstrap doesn't replace entry
    // objects either.
    expect(ensureRegistryPromise("captured")).toBe(captured);
  });
});
