/* eslint-disable @typescript-eslint/no-implied-eval, sonarjs/code-eval --
 * The Function constructor is the only realistic way to evaluate the
 * bootstrap script in the same realm as ensureRegistryPromise. The script
 * source is generated by getDeferBootstrapScript() — a const string — so
 * there is no untrusted-input path. */

import { afterEach, describe, expect, it, vi } from "vitest";

import {
  __resetRegistryForTests,
  ensureRegistryPromise,
  escapeForScript,
  formatSettleScript,
  getDeferBootstrapScript,
} from "../../src/shared-ssr/deferRegistry";

describe("@real-router/ssr-data-plugin deferRegistry", () => {
  afterEach(() => {
    __resetRegistryForTests();
  });

  describe("ensureRegistryPromise", () => {
    it("creates a pending promise on first access", () => {
      const promise = ensureRegistryPromise("reviews");

      expect(promise).toBeInstanceOf(Promise);
    });

    it("returns the same promise across calls (reference identity)", () => {
      const a = ensureRegistryPromise("reviews");
      const b = ensureRegistryPromise("reviews");

      expect(a).toBe(b);
    });

    it("isolates different keys", () => {
      const a = ensureRegistryPromise("reviews");
      const b = ensureRegistryPromise("related");

      expect(a).not.toBe(b);
    });

    it("resolves when bootstrap script settles the entry", async () => {
      const bootstrap = getDeferBootstrapScript();
      // Install bootstrap into the same realm as ensureRegistryPromise.
      const registryBefore = (globalThis as { __rrDeferRegistry__?: unknown })
        .__rrDeferRegistry__;

      expect(registryBefore).toBeUndefined();

      new Function(bootstrap)();

      const settle = (
        globalThis as {
          __rrDefer__?: (k: string, j: string) => void;
        }
      ).__rrDefer__;

      expect(settle).toBeTypeOf("function");

      const promise = ensureRegistryPromise("reviews");

      settle!("reviews", JSON.stringify({ count: 3 }));

      await expect(promise).resolves.toStrictEqual({ count: 3 });
    });

    it("rejects via __rrDeferError__ with Error reconstruction", async () => {
      new Function(getDeferBootstrapScript())();

      const reject = (
        globalThis as {
          __rrDeferError__?: (k: string, j: string) => void;
        }
      ).__rrDeferError__;

      const promise = ensureRegistryPromise("reviews");

      reject!(
        "reviews",
        JSON.stringify({ name: "FetchError", message: "503 unavailable" }),
      );

      await expect(promise).rejects.toMatchObject({
        name: "FetchError",
        message: "503 unavailable",
      });
    });

    it("falls back to default error message when payload lacks message", async () => {
      new Function(getDeferBootstrapScript())();

      const reject = (
        globalThis as {
          __rrDeferError__?: (k: string, j: string) => void;
        }
      ).__rrDeferError__;

      const promise = ensureRegistryPromise("k");

      reject!("k", JSON.stringify({}));

      await expect(promise).rejects.toMatchObject({
        message: "deferred error",
      });
    });
  });

  describe("getDeferBootstrapScript", () => {
    it("returns idempotent installer", () => {
      const script = getDeferBootstrapScript();

      new Function(script)();
      const first = (globalThis as { __rrDeferRegistry__?: unknown })
        .__rrDeferRegistry__;

      new Function(script)();
      const second = (globalThis as { __rrDeferRegistry__?: unknown })
        .__rrDeferRegistry__;

      expect(first).toBe(second);
    });

    it("does not throw in non-DOM environments (uses globalThis fallback chain)", () => {
      expect(() => new Function(getDeferBootstrapScript())()).not.toThrow();
    });
  });

  describe("escapeForScript", () => {
    it("returns a quoted JS string literal (drop straight into a script template)", () => {
      const out = escapeForScript("plain");

      expect(out.startsWith('"')).toBe(true);
      expect(out.endsWith('"')).toBe(true);
      // Round-trip: JSON.parse on a JS string literal === the original string.
      expect(JSON.parse(out)).toBe("plain");
    });

    it("escapes `<` so the HTML parser cannot terminate the script tag", () => {
      const out = escapeForScript("foo</script>bar");

      expect(out).not.toMatch(/<\/script/);
      expect(out).not.toMatch(/</);
      expect(out).toBe(String.raw`"foo\u003c/script\u003ebar"`);
    });

    it("escapes `>`", () => {
      const out = escapeForScript("a>b");

      expect(out).toBe(String.raw`"a\u003eb"`);
    });

    it("escapes `&` (defence-in-depth against entity processing)", () => {
      const out = escapeForScript("a&b");

      expect(out).toBe(String.raw`"a\u0026b"`);
    });

    it("escapes case-insensitive </SCRIPT> (no `<` reaches the HTML parser)", () => {
      const out = escapeForScript("foo</SCRIPT>bar");

      expect(out).not.toMatch(/<\/script/i);
    });

    it("escapes U+2028 (line separator)", () => {
      const lineSeparator = String.fromCodePoint(0x20_28);

      expect(escapeForScript(`a${lineSeparator}b`)).toContain(
        String.raw`a\u2028b`,
      );
    });

    it("escapes U+2029 (paragraph separator)", () => {
      const paraSeparator = String.fromCodePoint(0x20_29);

      expect(escapeForScript(`a${paraSeparator}b`)).toContain(
        String.raw`a\u2029b`,
      );
    });

    it("round-trips arbitrary unicode (key path: JS literal \u2192 original)", () => {
      const original =
        "\u043A\u043B\u044E\u0447-\u00E9-\uD83D\uDE80-</script>-&-</SCRIPT>";

      expect(JSON.parse(escapeForScript(original))).toBe(original);
    });

    it("round-trips JSON-shaped value (value path: JS literal \u2192 JSON.parse \u2192 original)", () => {
      const value = { evil: "</script><script>alert(1)</script>", n: 42 };
      const json = JSON.stringify(value);
      const literal = escapeForScript(json);
      const jsParsed = JSON.parse(literal);
      const back = JSON.parse(jsParsed);

      expect(back).toStrictEqual(value);
    });

    // Defensive guard: a misbehaving custom serializer or a TS-cast
    // callsite can smuggle a non-string in. JSON.stringify can fail in
    // three ways for non-strings \u2014 we collapse all to the JSON `null`
    // literal so the downstream `.replace` chain never throws and the
    // emitted script body always parses.
    it("emits JSON null for inputs JSON.stringify returns undefined for", () => {
      expect(escapeForScript(undefined as unknown as string)).toBe("null");
      expect(escapeForScript(Symbol("x") as unknown as string)).toBe("null");
      expect(escapeForScript((() => 1) as unknown as string)).toBe("null");
    });

    it("emits JSON null for inputs JSON.stringify throws on (BigInt)", () => {
      expect(escapeForScript(1n as unknown as string)).toBe("null");
    });

    it("emits JSON null for inputs JSON.stringify throws on (circular)", () => {
      const circular: Record<string, unknown> = {};

      circular.self = circular;

      expect(escapeForScript(circular as unknown as string)).toBe("null");
    });

    it("preserves the JSON literal when stringify returns 'null' as a string", () => {
      expect(escapeForScript(null as unknown as string)).toBe("null");
    });

    it("stringifies number/boolean inputs without throwing", () => {
      expect(escapeForScript(42 as unknown as string)).toBe("42");
      expect(escapeForScript(true as unknown as string)).toBe("true");
    });
  });

  describe("formatSettleScript", () => {
    it("emits __rrDefer__ for resolved values", () => {
      const out = formatSettleScript("reviews", '{"count":3}', false);

      expect(out).toMatch(/^<script>__rrDefer__\("reviews",/);
      expect(out.endsWith("</script>")).toBe(true);
    });

    it("emits __rrDeferError__ for rejected values", () => {
      const out = formatSettleScript("k", '{"message":"boom"}', true);

      expect(out).toContain("__rrDeferError__");
    });

    it("escapes </script> inside payload value", () => {
      const malicious = '{"x":"</script><script>alert(1)</script>"}';
      const out = formatSettleScript("k", malicious, false);

      expect(out).not.toMatch(/<\/script><script>alert/);
      expect(out).toContain(String.raw`</script>`);
    });

    it("escapes </script> inside payload key (the dangerous untrusted-input path)", () => {
      const out = formatSettleScript(
        '");alert(1);//</script><script>alert(2)</script>',
        '"v"',
        false,
      );

      // No HTML-parser-terminating sequence anywhere except the wrapping <script> tags.
      const innerBody = out.slice("<script>".length, -"</script>".length);

      expect(innerBody).not.toMatch(/<\/script/i);
      expect(innerBody).not.toMatch(/</);
    });

    it("escapes JS-special chars in the key", () => {
      const out = formatSettleScript('weird"key', '"v"', false);

      expect(out).toContain(String.raw`"weird\"key"`);
    });
  });

  describe("__resetRegistryForTests", () => {
    it("clears the registry and globals", () => {
      new Function(getDeferBootstrapScript())();
      void ensureRegistryPromise("k");

      expect(
        (globalThis as { __rrDeferRegistry__?: unknown }).__rrDeferRegistry__,
      ).toBeDefined();

      __resetRegistryForTests();

      expect(
        (globalThis as { __rrDeferRegistry__?: unknown }).__rrDeferRegistry__,
      ).toBeUndefined();
      expect(
        (globalThis as { __rrDefer__?: unknown }).__rrDefer__,
      ).toBeUndefined();
      expect(
        (globalThis as { __rrDeferError__?: unknown }).__rrDeferError__,
      ).toBeUndefined();
    });
  });

  describe("registry observability", () => {
    it("ensureRegistryPromise survives multiple keys without leaking", () => {
      const keys = ["a", "b", "c", "d"];
      const promises = keys.map((k) => ensureRegistryPromise(k));

      expect(new Set(promises).size).toBe(keys.length);
    });

    it("ensureRegistryPromise is callable in vitest's jsdom-less env", () => {
      expect(() => ensureRegistryPromise("smoke")).not.toThrow();
    });

    it("vi.unstubAllGlobals does not affect registry (sanity)", () => {
      const promise = ensureRegistryPromise("k");

      vi.unstubAllGlobals();

      expect(ensureRegistryPromise("k")).toBe(promise);
    });
  });
});
