// sync-config.test.mjs — the generated regions of configuration files: what
// `--check` and `--write` read, what they refuse, and what they write.
//
// Run:  node --test scripts/tests/sync-config.test.mjs
//
// The cells run `main` on a fixture git work tree with `packages/` and two
// regions: one in a `.properties` file rendered from the package walk, one
// constant and indented as in a workflow. Every refusal of a run that could
// write is asserted to write nothing, with another region of the tree out of
// step, so a write that slipped through would show.

import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

import { withoutGitEnv } from "../git-env.mjs";
import { packages } from "../repo-model.mjs";
import { REGIONS, findRegions, lineDiff, main } from "../sync-config.mjs";

const repoRoot = dirname(dirname(dirname(fileURLToPath(import.meta.url))));

const PROPS = "conf/sonar.properties";
const YAML = "conf/workflow.yml";

/** A region from the package walk, and a constant one at a YAML indentation. */
const MODULES = {
  name: "modules",
  file: PROPS,
  source: "packages/*/package.json",
  render: (root) => [
    `sonar.modules=${packages(root)
      .map((pkg) => pkg.name)
      .join(",")}`,
  ],
};
const STEPS = {
  name: "steps",
  file: YAML,
  source: "the build's step list",
  render: () => ["      - one", "      - two"],
};
const FIXTURE_REGIONS = [MODULES, STEPS];

const open = (name, indent = "", source = "the fixture") =>
  `${indent}# >>> sync-config: ${name} — generated by scripts/sync-config.mjs from ${source}; edit the source, then run --write`;
const close = (name, indent = "") => `${indent}# <<< sync-config: ${name}`;

const PROPS_LINES = [
  "# The fixture's settings.",
  "sonar.projectKey=fx",
  open("modules", "", MODULES.source),
  "sonar.modules=a,b",
  close("modules"),
  "sonar.sources=src",
  "",
];
const YAML_LINES = [
  "jobs:",
  "  build:",
  "    steps:",
  open("steps", "      ", STEPS.source),
  "      - one",
  "      - two",
  close("steps", "      "),
  "  after: true",
  "",
];

/** A tree in step: two packages, and each region holding what it renders. */
const tree = ({ props = PROPS_LINES, yaml = YAML_LINES } = {}) => ({
  "packages/a/package.json": JSON.stringify({ name: "@fx/a" }),
  "packages/b/package.json": JSON.stringify({ name: "@fx/b" }),
  [PROPS]: props.join("\n"),
  [YAML]: yaml.join("\n"),
});

/** The same tree with the YAML region out of step. */
const yamlOutOfStep = YAML_LINES.map((line) =>
  line === "      - two" ? "      - three" : line,
);

/**
 * Builds `files` as a git work tree under a fresh directory, runs `body` on
 * it, removes it. A file given as a Buffer is written byte for byte.
 */
function withTree(files, body) {
  const root = mkdtempSync(join(tmpdir(), "sync-config-"));
  try {
    for (const [file, text] of Object.entries(files)) {
      mkdirSync(dirname(join(root, file)), { recursive: true });
      writeFileSync(join(root, file), text);
    }
    const env = withoutGitEnv(process.env);
    execFileSync("git", ["init", "-q"], { cwd: root, env });
    execFileSync("git", ["add", "-A"], { cwd: root, env });
    return body(root);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

const readAll = (root, files) =>
  Object.fromEntries(
    Object.keys(files).map((file) => [file, readFileSync(join(root, file))]),
  );
const bytes = (files) =>
  Object.fromEntries(
    Object.entries(files).map(([file, text]) => [file, Buffer.from(text)]),
  );

/** Runs `main` and keeps what it prints. */
function run(args, root, regions = FIXTURE_REGIONS) {
  const log = [];
  const error = [];
  const code = main(args, root, regions, {
    log: (line) => log.push(line),
    error: (line) => error.push(line),
  });
  return { code, log: log.join("\n"), error: error.join("\n") };
}

/** A refusal: the run fails with `message`, and neither file changes. */
function refused(files, message, regions = FIXTURE_REGIONS) {
  withTree(files, (root) => {
    for (const mode of ["--check", "--write"]) {
      const result = run([mode], root, regions);
      assert.equal(result.code, 1, `${mode}: ${result.log}`);
      assert.match(result.error, message);
      assert.match(result.error, /nothing written/);
    }
    assert.deepEqual(readAll(root, files), bytes(files));
  });
}

test("CONTROL — --check passes a tree whose regions hold what they render", () => {
  withTree(tree(), (root) => {
    const result = run(["--check"], root);
    assert.equal(result.code, 0, result.error);
    assert.match(
      result.log,
      /✓ sync-config: 2 region\(s\) in 2 file\(s\) in step with their sources/,
    );
  });
});

for (const [name, edit] of Object.entries({
  "an edited line": (lines) =>
    lines.map((line) =>
      line === "sonar.modules=a,b" ? "sonar.modules=a" : line,
    ),
  "a deleted line": (lines) =>
    lines.filter((line) => line !== "sonar.modules=a,b"),
  "an added line": (lines) =>
    lines.flatMap((line) =>
      line === "sonar.modules=a,b" ? [line, "sonar.added=1"] : [line],
    ),
})) {
  test(`a hand change inside a region — ${name} — fails --check, which names it, shows the difference and writes nothing`, () => {
    const files = tree({ props: edit(PROPS_LINES) });
    withTree(files, (root) => {
      const result = run(["--check"], root);
      assert.equal(result.code, 1);
      assert.match(
        result.log,
        /differs: conf\/sonar\.properties — region "modules"/,
      );
      assert.match(result.log, /^ {4}[-+] /m);
      assert.match(result.error, /1 of 2 region\(s\) in 2 file\(s\) differ/);
      assert.deepEqual(readAll(root, files), bytes(files));
    });
  });
}

test("a region follows its source: a new package fails --check, and --write takes it in", () => {
  withTree(
    { ...tree(), "packages/c/package.json": JSON.stringify({ name: "@fx/c" }) },
    (root) => {
      assert.equal(run(["--check"], root).code, 1);
      assert.equal(run(["--write"], root).code, 0);
      assert.ok(
        readFileSync(join(root, PROPS), "utf8").includes(
          "sonar.modules=a,b,c\n",
        ),
      );
      assert.equal(run(["--check"], root).code, 0);
    },
  );
});

test("--write rewrites the regions and nothing else, and a second --write changes nothing", () => {
  const props = [
    "sonar.projectKey=changed-by-hand",
    open("modules", "", MODULES.source),
    "sonar.modules=stale",
    "sonar.extra=stale",
    close("modules"),
    "sonar.sources=lib",
    "",
  ];
  withTree(tree({ props, yaml: yamlOutOfStep }), (root) => {
    const first = run(["--write"], root);
    assert.equal(first.code, 0, first.error);
    assert.match(first.log, /rewrote 2$/m);

    assert.equal(
      readFileSync(join(root, PROPS), "utf8"),
      [
        "sonar.projectKey=changed-by-hand",
        open("modules", "", MODULES.source),
        "sonar.modules=a,b",
        close("modules"),
        "sonar.sources=lib",
        "",
      ].join("\n"),
    );
    assert.equal(readFileSync(join(root, YAML), "utf8"), YAML_LINES.join("\n"));

    const written = readAll(root, tree());
    const second = run(["--write"], root);
    assert.equal(second.code, 0);
    assert.match(second.log, /in step with their sources/);
    assert.deepEqual(readAll(root, tree()), written);
  });
});

test("two regions of one file are both rewritten, the upper one changing its length", () => {
  const TAIL = {
    name: "tail",
    file: PROPS,
    source: "the tail",
    render: () => ["sonar.tail=1"],
  };
  const props = [
    "sonar.projectKey=fx",
    open("modules", "", MODULES.source),
    "x=1",
    "x=2",
    "x=3",
    close("modules"),
    "between=1",
    open("tail", "", TAIL.source),
    "sonar.tail=0",
    close("tail"),
    "",
  ];
  withTree(tree({ props }), (root) => {
    const result = run(["--write"], root, [...FIXTURE_REGIONS, TAIL]);
    assert.equal(result.code, 0, result.error);
    assert.equal(
      readFileSync(join(root, PROPS), "utf8"),
      [
        "sonar.projectKey=fx",
        open("modules", "", MODULES.source),
        "sonar.modules=a,b",
        close("modules"),
        "between=1",
        open("tail", "", TAIL.source),
        "sonar.tail=1",
        close("tail"),
        "",
      ].join("\n"),
    );
  });
});

// Each departure from "one ordered pair of a known name", planted in the
// properties file while the YAML region is out of step.
const INNER = {
  name: "inner",
  file: PROPS,
  source: "the inner",
  render: () => ["sonar.inner=1"],
};
const MARKER_STATES = {
  "a missing opening marker": [
    (lines) =>
      lines.filter((line) => !line.startsWith("# >>> sync-config: modules")),
    /region "modules" needs one opening and one closing marker, and has 0 and 1/,
  ],
  "a missing closing marker": [
    (lines) => lines.filter((line) => line !== close("modules")),
    /region "modules" needs one opening and one closing marker, and has 1 and 0/,
  ],
  "a repeated opening marker": [
    (lines) => [open("modules", "", MODULES.source), ...lines],
    /region "modules" needs one opening and one closing marker, and has 2 and 1/,
  ],
  "a repeated closing marker": [
    (lines) => [...lines, close("modules")],
    /region "modules" needs one opening and one closing marker, and has 1 and 2/,
  ],
  "markers in reverse order": [
    (lines) =>
      lines.map((line) =>
        line.startsWith("# >>> sync-config: modules")
          ? close("modules")
          : line === close("modules")
            ? open("modules", "", MODULES.source)
            : line,
      ),
    /region "modules" closes before it opens/,
  ],
  "markers of another region nested inside": [
    (lines) =>
      lines.flatMap((line) =>
        line === "sonar.modules=a,b"
          ? [
              open("inner", "", INNER.source),
              "sonar.inner=1",
              close("inner"),
              line,
            ]
          : [line],
      ),
    /a marker of region "inner" inside region "modules"/,
    [...FIXTURE_REGIONS, INNER],
  ],
  "a marker of a name no region has": [
    (lines) => [...lines, open("ghost"), close("ghost")],
    /a marker of region "ghost", which this file does not hold/,
  ],
  "a marker of a region another file holds": [
    (lines) => [...lines, open("steps"), close("steps")],
    /a marker of region "steps", which this file does not hold/,
  ],
  "markers at different indentations": [
    (lines) =>
      lines.map((line) => (line === close("modules") ? `  ${line}` : line)),
    /region "modules" closes at another indentation than it opens/,
  ],
  "an opening marker that names no source": [
    (lines) =>
      lines.map((line) =>
        line.startsWith("# >>> sync-config: modules")
          ? "# >>> sync-config: modules — generated, see the script"
          : line,
      ),
    /the opening marker of region "modules" does not name its source, packages\/\*\/package\.json/,
  ],
};

for (const [name, [plant, message, regions]] of Object.entries(MARKER_STATES)) {
  test(`marker state: ${name} fails the run and writes nothing`, () => {
    refused(
      tree({ props: plant(PROPS_LINES), yaml: yamlOutOfStep }),
      message,
      regions,
    );
  });
}

for (const lookalike of [
  "#>>> sync-config: modules",
  "// >>> sync-config: modules",
  "# >>> sync-config:modules",
  "# >>> sync-config: Modules",
  "# >>> sync-config: modules",
  "# <<<sync-config: modules",
  "# <<< sync-config: modules trailing",
  "  # >>> sync-config: modules trailing",
  "# >> sync-config: modules",
  "# >>> SYNC-CONFIG: modules",
  "# >>> sync_config: modules",
  "# sync-config >>> modules",
  "sonar.x=1 # >>> sync-config: modules — a header",
]) {
  test(`a line that names a marker in another form fails the run: ${lookalike}`, () => {
    refused(
      tree({
        props: [...PROPS_LINES.slice(0, -1), lookalike, ""],
        yaml: yamlOutOfStep,
      }),
      /a line that names a sync-config marker but is not one/,
    );
  });
}

test("a marker in a tracked file no region names fails the run", () => {
  refused(
    {
      ...tree({ yaml: yamlOutOfStep }),
      "conf/copy.yml": [open("ghost"), "x: 1", close("ghost"), ""].join("\n"),
    },
    /conf\/copy\.yml: holds a sync-config marker, and no region names the file/,
  );
});

test("a region listed twice fails the run", () => {
  refused(tree({ yaml: yamlOutOfStep }), /region "modules" is listed twice/, [
    ...FIXTURE_REGIONS,
    MODULES,
  ]);
});

test("a source the region cannot read fails the run and names the region", () => {
  refused(
    tree({ yaml: yamlOutOfStep }),
    /region "modules": the source holds an entry it cannot carry over/,
    [
      {
        ...MODULES,
        render: () => {
          throw new Error("the source holds an entry it cannot carry over");
        },
      },
      STEPS,
    ],
  );
});

for (const [name, line, message] of [
  ["a line break", "a\nb", /renders a line it cannot hold/],
  ["a carriage return", "x\r", /renders a line it cannot hold/],
  ["a byte-order mark", "\uFEFFx", /renders a line it cannot hold/],
  ["a marker", open("modules"), /renders a line it cannot hold/],
  [
    "a line shallower than its markers",
    "    - one",
    /region "steps" renders a line shallower than its markers/,
  ],
]) {
  test(`a rendered line holding ${name} fails the run`, () => {
    const regions = name.includes("shallower")
      ? [MODULES, { ...STEPS, render: () => [line] }]
      : [{ ...MODULES, render: () => [line] }, STEPS];
    const files = name.includes("shallower")
      ? tree({
          props: PROPS_LINES.map((l) =>
            l === "sonar.modules=a,b" ? "sonar.modules=a" : l,
          ),
        })
      : tree({ yaml: yamlOutOfStep });
    refused(files, message, regions);
  });
}

// A properties file is read whole: a setting outside a region can undo it.
const PROPERTIES_CASES = {
  "the region's key set again below it": [
    (lines) => [...lines.slice(0, -1), "sonar.modules=x", ""],
    /sonar\.modules is set outside region "modules" too, and the last setting wins/,
  ],
  "the region's key set above it": [
    (lines) => ["sonar.modules=x", ...lines],
    /sonar\.modules is set outside region "modules" too/,
  ],
  "a line continuing into the opening marker": [
    (lines) =>
      lines.map((line) =>
        line === "sonar.projectKey=fx" ? "sonar.projectKey=fx,\\" : line,
      ),
    /the line continues into the opening marker below it/,
  ],
  "a line outside the regions it does not read": [
    (lines) => ["sonar.key value", ...lines],
    /a properties line this does not read: sonar\.key value/,
  ],
};

for (const [name, [plant, message]] of Object.entries(PROPERTIES_CASES)) {
  test(`properties: ${name} fails the run`, () => {
    refused(tree({ props: plant(PROPS_LINES), yaml: yamlOutOfStep }), message);
  });
}

for (const [name, body, message] of [
  [
    "a last line that continues into the closing marker",
    ["sonar.modules=a,\\"],
    /region "modules" ends in a line that continues into its closing marker/,
  ],
  [
    "a line it does not read",
    ["sonar.modules a,b"],
    /region "modules" renders a properties line this does not read/,
  ],
]) {
  test(`properties: a region rendering ${name} fails the run`, () => {
    refused(tree({ yaml: yamlOutOfStep }), message, [
      { ...MODULES, render: () => body },
      STEPS,
    ]);
  });
}

test("properties: a continued setting inside a region is read as one", () => {
  withTree(tree(), (root) => {
    const regions = [
      { ...MODULES, render: () => ["sonar.modules=a,\\", "  b"] },
      STEPS,
    ];
    assert.equal(run(["--write"], root, regions).code, 0);
    assert.equal(run(["--check"], root, regions).code, 0);
  });
});

test("properties: a line ending in an escaped backslash does not continue", () => {
  withTree(tree(), (root) => {
    const regions = [
      { ...MODULES, render: () => ["sonar.modules=C:\\\\"] },
      STEPS,
    ];
    assert.equal(run(["--write"], root, regions).code, 0);
    assert.equal(run(["--check"], root, regions).code, 0);
  });
});

test("a hook's git variables do not reach the scan for markers", () => {
  const saved = { dir: process.env.GIT_DIR, index: process.env.GIT_INDEX_FILE };
  withTree(tree(), (root) => {
    process.env.GIT_DIR = join(root, "no-such-repository");
    process.env.GIT_INDEX_FILE = join(root, "no-such-index");
    try {
      const result = run(["--check"], root);
      assert.equal(result.code, 0, result.error);
    } finally {
      for (const [key, value] of [
        ["GIT_DIR", saved.dir],
        ["GIT_INDEX_FILE", saved.index],
      ]) {
        if (value === undefined) delete process.env[key];
        else process.env[key] = value;
      }
    }
  });
});

for (const [name, text] of [
  ["CRLF line endings", PROPS_LINES.join("\r\n")],
  ["a byte-order mark", `\uFEFF${PROPS_LINES.join("\n")}`],
  [
    "a tab",
    PROPS_LINES.join("\n").replace("sonar.sources=src", "sonar.sources=\tsrc"),
  ],
  [
    "a NEL",
    PROPS_LINES.join("\n").replace(
      "sonar.sources=src",
      "sonar.sources=\u0085src",
    ),
  ],
  [
    "an LS",
    PROPS_LINES.join("\n").replace("sonar.sources=src", "sonar.sources= src"),
  ],
]) {
  test(`a region file holding ${name} fails the run`, () => {
    refused(
      { ...tree({ yaml: yamlOutOfStep }), [PROPS]: text },
      /holds a line break other than LF, a byte-order mark or a control character/,
    );
  });
}

test("a region file that is not UTF-8 fails the run", () => {
  refused(
    {
      ...tree({ yaml: yamlOutOfStep }),
      [PROPS]: Buffer.concat([
        Buffer.from("# caf"),
        Buffer.from([0xe9]),
        Buffer.from(`\n${PROPS_LINES.join("\n")}`),
      ]),
    },
    /conf\/sonar\.properties: The encoded data was not valid for encoding utf-8/,
  );
});

test("a region whose file is missing fails the run", () => {
  refused(tree({ yaml: yamlOutOfStep }), /conf\/missing\.properties: ENOENT/, [
    ...FIXTURE_REGIONS,
    {
      name: "lost",
      file: "conf/missing.properties",
      source: "nothing",
      render: () => [],
    },
  ]);
});

test("without one mode flag, the run prints its usage and reads and writes nothing", () => {
  const files = tree({ yaml: yamlOutOfStep });
  withTree(files, (root) => {
    for (const args of [
      [],
      ["--fix"],
      ["--check", "--write"],
      ["--write", "x"],
    ]) {
      const result = run(args, root);
      assert.equal(result.code, 2, JSON.stringify(args));
      assert.equal(result.error, "usage: sync-config.mjs --check | --write");
      assert.equal(result.log, "");
    }
    assert.deepEqual(readAll(root, files), bytes(files));
  });
});

test("findRegions gives each region the lines of its markers, its indentation and header", () => {
  const { spans, errors } = findRegions(YAML, YAML_LINES, ["steps"]);
  assert.deepEqual(errors, []);
  assert.deepEqual(spans.get("steps"), {
    open: 3,
    close: 6,
    indent: "      ",
    header: `generated by scripts/sync-config.mjs from ${STEPS.source}; edit the source, then run --write`,
  });
});

test("lineDiff marks what --check prints", () => {
  assert.deepEqual(lineDiff(["a", "b", "c"], ["a", "x", "c", "d"]), [
    "  a",
    "- b",
    "+ x",
    "  c",
    "+ d",
  ]);
});

// ── The repository.

test("the regions this repository keeps", () => {
  assert.deepEqual(
    REGIONS.map((region) => `${region.file}#${region.name}`),
    [
      "sonar-project.properties#cpd-exclusions",
      "sonar-project.properties#coverage-exclusions",
      ".github/dependency-review-config.yml#allow-ghsas",
    ],
  );
});

const COVERAGE = REGIONS.find(
  (region) => region.name === "coverage-exclusions",
);

/** A package with tests and the vitest config `config`. */
const tested = (name, config) => ({
  [`packages/${name}/package.json`]: JSON.stringify({ name: `@fx/${name}` }),
  [`packages/${name}/src/index.ts`]: "export const one = 1;\n",
  [`packages/${name}/tests/one.test.ts`]: "\n",
  [`packages/${name}/vitest.config.mts`]: config,
});

test("coverage-exclusions holds the src/ of each package without tests or below 100 % thresholds", () => {
  withTree(
    {
      ...tested("clean", "export default {};\n"),
      ...tested("phantom", "thresholds: { branches: 99 }\n"),
      "packages/untested/package.json": JSON.stringify({
        name: "@fx/untested",
      }),
      "packages/untested/src/index.ts": "export const one = 1;\n",
      // No src/ of its own: nothing for Sonar to index.
      "packages/bare/package.json": JSON.stringify({ name: "@fx/bare" }),
    },
    (root) => {
      assert.deepEqual(COVERAGE.render(root), [
        "sonar.coverage.exclusions=packages/phantom/src/**,packages/untested/src/**",
      ]);
    },
  );
});

test("a threshold written only in a comment keeps the package out of coverage-exclusions", () => {
  withTree(
    tested(
      "noted",
      "// thresholds: { branches: 94 }\nthresholds: { branches: 100 }\n",
    ),
    (root) => {
      assert.deepEqual(COVERAGE.render(root), ["sonar.coverage.exclusions="]);
    },
  );
});

test("a threshold the package walk cannot read fails the run and names the region and the file", () => {
  const files = {
    ...tested("odd", "thresholds: { branches: FLOOR }\n"),
    "sonar-project.properties": [
      open("coverage-exclusions", "", COVERAGE.source),
      "sonar.coverage.exclusions=",
      close("coverage-exclusions"),
      "",
    ].join("\n"),
  };
  refused(
    files,
    /region "coverage-exclusions": packages\/odd\/vitest\.config\.mts:1: "branches: FLOOR" — isPhantom reads a coverage threshold only as/,
    [COVERAGE],
  );
});

test("on the repository, the command line checks exactly the regions REGIONS lists, and refuses no flag", () => {
  const script = join(repoRoot, "scripts", "sync-config.mjs");
  const files = new Set(REGIONS.map((region) => region.file)).size;
  const check = spawnSync(process.execPath, [script, "--check"], {
    encoding: "utf8",
  });
  assert.equal(check.status, 0, check.stderr);
  assert.equal(
    check.stdout,
    `✓ sync-config: ${REGIONS.length} region(s) in ${files} file(s) in step with their sources\n`,
  );

  const bare = spawnSync(process.execPath, [script], { encoding: "utf8" });
  assert.equal(bare.status, 2);
  assert.equal(bare.stderr, "usage: sync-config.mjs --check | --write\n");
});
