#!/bin/bash

# Prose linting for the Markdown corpus, via Vale.
#
# ⚑ WHY only `.md`. The source tree already has better guards than a word list:
# `comment-historiography-authority` calibrates "used to" against the
# instrumental sense, and its count table excludes framework versions and
# distances by lookbehind. Vale has neither lookbehind nor that calibration, so
# pointing it at `packages/*/src` would replace a precise ratchet with a blunt
# one. What `.md` has is the opposite problem: the #2111 census READ those 29
# files, but no FORM ratchet reaches them at all.
#
# Scope comes from `.vale.ini`, and gitignored trees — `.claude/**` above all —
# are out of it by owner decision.
#
# Skips gracefully when Vale is absent, matching lint:audit and lint:security:
# a fresh clone is never wedged. Install with:
#   brew install vale
#
# ⚠ That skip is what makes this a GATE only where Vale is guaranteed. Set
# `VALE_REQUIRED=1` and a missing binary FAILS instead: CI sets it, so an
# install step that silently broke reds the job rather than reporting a clean
# corpus it never read. `lint:issue-refs` shipped the opposite bug first — every
# non-zero exit read as "no network", and a planted bad reference passed.
#
# Usage: ./scripts/check-prose.sh [path ...]

set -e

if ! command -v vale >/dev/null 2>&1; then
  if [ -n "${VALE_REQUIRED:-}" ]; then
    echo "❌ vale not found and VALE_REQUIRED is set — refusing to report a"
    echo "   corpus this run never read."
    exit 1
  fi

  echo "⚠️  vale not found — skipping prose lint."
  echo "    Install with: brew install vale"
  echo "    (Hook stays non-blocking; CI runs it with VALE_REQUIRED=1.)"
  exit 0
fi

# Tracked Markdown only: `git ls-files` excludes every ignored tree structurally,
# rather than by a list of directory names that is always one entry short.
#
# ⚠ Three exclusions, and each is a decision rather than a convenience:
#   - CHANGELOG.md is generated by changesets, and its prose is a record of what
#     shipped — the one place history BELONGS.
#   - `benchmarks/` and `examples/` are out of scope by owner decision: their
#     prose is separate work, on a different cadence, and mixing it in here
#     would make every run report findings nobody is going to act on today.
if [ "$#" -gt 0 ]; then
  TARGETS=("$@")
else
  # shellcheck disable=SC2207 # paths in this repository carry no spaces
  TARGETS=($(git ls-files '*.md' |
    grep -v 'CHANGELOG\.md$' |
    grep -v '^benchmarks/' |
    grep -v '^examples/'))
fi

if [ "${#TARGETS[@]}" -eq 0 ]; then
  echo "No Markdown to lint."
  exit 0
fi

echo "Linting ${#TARGETS[@]} Markdown file(s) with Vale…"
vale "${TARGETS[@]}"
