#!/bin/bash

# Prose linting for the Markdown corpus, via Vale.
#
# ⚑ WHY only `.md`. The source tree already has better guards than a word list:
# `comment-historiography-authority` calibrates "used to" against the
# instrumental sense, and its count table excludes framework versions and
# distances by lookbehind. Vale has neither lookbehind nor that calibration, so
# pointing it at `packages/*/src` would replace a precise ratchet with a blunt
# one. What `.md` has is the opposite problem: the #2111 census READ those 29
# files, but no FORM ratchet reaches them at all.
#
# Scope comes from `.vale.ini`, and gitignored trees — `.claude/**` above all —
# are out of it by owner decision.
#
# Skips gracefully when Vale is absent, matching lint:audit and lint:security:
# a fresh clone is never wedged. Install with:
#   brew install vale
#
# ⚠ That skip is what makes this a GATE only where Vale is guaranteed. Set
# `VALE_REQUIRED=1` and a missing binary FAILS instead: CI sets it, so an
# install step that silently broke reds the job rather than reporting a clean
# corpus it never read. `lint:issue-refs` shipped the opposite bug first — every
# non-zero exit read as "no network", and a planted bad reference passed.
#
# A Vale older than the version CI installs (`vale-styles/VERSION`) refuses with
# exit 3: the rules are checked against that version.
#
# Usage: ./scripts/check-prose.sh [path ...]
#        ./scripts/check-prose.sh --changed <base>
#   Paths are relative to the caller's cwd. With none, the corpus is the
#   repository's, from any directory. `--changed` lints the corpus files that
#   `<base>..HEAD` adds or edits — or the whole corpus, when the range edits
#   what decides the result: `.vale.ini`, `vale-styles/` or this script.

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if ! command -v vale >/dev/null 2>&1; then
  if [ -n "${VALE_REQUIRED:-}" ]; then
    echo "❌ vale not found and VALE_REQUIRED is set — refusing to report a"
    echo "   corpus this run never read."
    exit 1
  fi

  echo "⚠️  vale not found — skipping prose lint."
  echo "    Install with: brew install vale"
  echo "    (Hook stays non-blocking; CI runs it with VALE_REQUIRED=1.)"
  exit 0
fi

VALE_FLOOR="$(sed -n 's/^VALE_VERSION=//p' "$ROOT/vale-styles/VERSION" 2>/dev/null || true)"
vale_version="$(vale --version 2>/dev/null |
  sed -n 's/^vale version \([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/p')"
if [ -z "$VALE_FLOOR" ] || [ -z "$vale_version" ]; then
  echo "❌ Could not read the Vale version or its floor — the prose lint did NOT run."
  echo "   It must be ${VALE_FLOOR:-the one in vale-styles/VERSION} or newer: brew upgrade vale"
  exit 3
fi
# The lower of the two, field by field as numbers: as strings, 3.9.0 sorts
# above 3.20.0.
lower="$(printf '%s\n%s\n' "$VALE_FLOOR" "$vale_version" |
  sort -t . -k 1,1n -k 2,2n -k 3,3n | head -n 1)"
if [ "$lower" != "$VALE_FLOOR" ]; then
  echo "❌ vale $vale_version is below $VALE_FLOOR, the version CI installs — the prose lint did NOT run."
  echo "   Upgrade with: brew upgrade vale"
  exit 3
fi

# Tracked Markdown only: `git ls-files` excludes every ignored tree structurally,
# rather than by a list of directory names that is always one entry short.
#
# ⚠ Each exclusion is a decision rather than a convenience:
#   - CHANGELOG.md is generated by changesets, and its prose is a record of what
#     shipped — the one place history BELONGS.
#   - `benchmarks/`, `cross-router-bench/` and `examples/` are out of scope by
#     owner decision: their prose is separate work, on a different cadence, and
#     mixing it in here would make every run report findings nobody is going
#     to act on today.
#   - `.claude/` is out of scope by owner decision. Most of it is ignored, but
#     `git ls-files` still returns what of it is tracked — the skills among it —
#     and that has its own checks: `line-anchor-authority` reads it.
#
# `|| true`: when the exclusions remove every path — a release PR edits only
# CHANGELOG.md — grep exits 1, and `set -e` would stop the script before it
# says there is no Markdown to lint.
in_corpus() {
  grep -v 'CHANGELOG\.md$' |
    grep -v '^benchmarks/' |
    grep -v '^cross-router-bench/' |
    grep -v '^examples/' |
    grep -v '^\.claude/' || true
}

if [ "${1:-}" = "--changed" ]; then
  if [ -z "${2:-}" ]; then
    echo "❌ --changed needs a base: check-prose.sh --changed <base>"
    exit 2
  fi
  base="$2"
  # From the root, like the whole corpus: the paths git prints are the root's.
  cd "$ROOT"
  # No --diff-filter here: a deleted word list changes what Vale accepts.
  if ! rules="$(git diff --name-only "$base" HEAD -- .vale.ini vale-styles scripts/check-prose.sh)"; then
    echo "❌ git diff against $base failed — nothing was linted."
    exit 2
  fi
  if [ -n "$rules" ]; then
    echo "The range edits what decides the result — linting the whole corpus."
    # shellcheck disable=SC2207 # paths in this repository carry no spaces
    TARGETS=($(git ls-files '*.md' | in_corpus))
  else
    if ! changed="$(git diff --name-only --diff-filter=d "$base" HEAD -- '*.md')"; then
      echo "❌ git diff against $base failed — nothing was linted."
      exit 2
    fi
    # shellcheck disable=SC2207 # paths in this repository carry no spaces
    TARGETS=($(printf '%s\n' "$changed" | in_corpus))
  fi
elif [ "$#" -gt 0 ]; then
  TARGETS=("$@")
else
  # From the script's own location, never from the cwd (#2544): `git ls-files`
  # lists the files under the cwd, with paths relative to it, and the
  # exclusions above are written against paths from the root.
  cd "$ROOT"
  # shellcheck disable=SC2207 # paths in this repository carry no spaces
  TARGETS=($(git ls-files '*.md' | in_corpus))
fi

if [ "${#TARGETS[@]}" -eq 0 ]; then
  echo "No Markdown to lint."
  exit 0
fi

echo "Linting ${#TARGETS[@]} Markdown file(s) with Vale…"
vale "${TARGETS[@]}"
